import "@/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { TRPCReactProvider } from "@/trpc/react";
import { getServerUser } from "@/utils/supabase/server";
import { AuthProvider } from "@/providers/AuthProvider";

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const data = await getServerUser();

  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <TRPCReactProvider>
          <AuthProvider {...data}>{children}</AuthProvider>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
